### ISSUE TITLE
bad link? 404

### ISSUE THREAD

**Issue by atgreen** [pittar-demos/gitops-and-tekton-with-openshift#1]
Hey Andrew,

The URL you provide here is giving me a 404...

oc apply -k https://github.com/pittar-demos/gitops-and-tekton-with-openshift/argocd/argocd?ref=main

**Comment by pittar** [comment]
Thanks @atgreen , I'll take a look.  I'm actually fixing up the README right now.

Also, what ever of "oc" are you using?  I'm using 4.7.0.

**Comment by pittar** [comment]
It worked for me, so I suspect it's your version of oc?

```
$ oc apply -k https://github.com/pittar-demos/gitops-and-tekton-with-openshift/argocd/argocd?ref=main
appproject.argoproj.io/argocd-devs unchanged
application.argoproj.io/argocd-devs configured
```

**Comment by atgreen** [comment]
My bad -- I was just looking at the link with the browser, wanting to see what it was.  How did you come up with that URL?

**Comment by pittar** [comment]
Mostly from looking at other examples.  

You take "/tree/main" out of the URL you would see in the browser.  This would be the browser link to that directory. 

https://github.com/pittar-demos/gitops-and-tekton-with-openshift/tree/main/argocd/argocd
